# Frontend API Integration Contract
# Feature: 007-chatkit-frontend
# These are the EXISTING backend endpoints the frontend will consume.
# No new endpoints are created by this feature.

openapi: 3.0.3
info:
  title: Chat API (consumed by frontend)
  version: 1.0.0
  description: Existing backend endpoints from spec 006 that the frontend chat UI integrates with.

paths:
  /api/chat:
    post:
      operationId: sendChatMessage
      summary: Send a chat message and receive AI response
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: User's natural language message
                  maxLength: 4000
                conversation_id:
                  type: string
                  format: uuid
                  nullable: true
                  description: Omit to start a new conversation
      responses:
        '200':
          description: AI response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Validation error (empty message, exceeds length)
        '401':
          description: Authentication required
        '404':
          description: Conversation not found
        '503':
          description: AI provider unavailable

  /api/conversations:
    get:
      operationId: listConversations
      summary: List user's conversations
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Conversation list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationListResponse'
        '401':
          description: Authentication required

  /api/conversations/{conversation_id}:
    get:
      operationId: getConversation
      summary: Get conversation with message history
      security:
        - bearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 200
      responses:
        '200':
          description: Conversation detail with messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDetailResponse'
        '401':
          description: Authentication required
        '404':
          description: Conversation not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatResponse:
      type: object
      properties:
        conversation_id:
          type: string
          format: uuid
        message:
          type: string
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCallInfo'

    ToolCallInfo:
      type: object
      properties:
        tool_name:
          type: string
        arguments:
          type: object
        result:
          type: string
        success:
          type: boolean

    ConversationListResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationSummary'
        total_count:
          type: integer

    ConversationSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        message_count:
          type: integer

    ConversationDetailResponse:
      type: object
      properties:
        conversation:
          $ref: '#/components/schemas/ConversationSummary'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessageInfo'

    MessageInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string
        tool_calls:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ToolCallInfo'
        tool_call_id:
          type: string
          nullable: true
        tool_name:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
