apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: flowtodo-secrets
        key: DATABASE_URL
    - name: schema
      value: "public"
    - name: tableName
      value: "dapr_state"
